### ISSUE TITLE
Semver imports

### ISSUE THREAD

**Issue by dselman** [accordproject/concerto#931]
# Feature Request 🛍️

Support imports across semver ranges.

## Use Case

Allows less strict management of imports, meaning that when an imported namespace is referenced, if backwards compatible changes to the imported namespace are made, then the version number of the importing namespace does not have to be incremented.

## Possible Solution

Support some form of semver range for import statements:

```
namespace person@1.0.0

concept Person {
   o String name
}
```

With strict import (as today):

```
namespace vehicle@1.0.0

import person@1.0.0.{Person}

concept Vehicle {
   o Person owner
}
```

With semver import:

```
namespace vehicle@1.0.0

import person@1.x.{Person}

concept Vehicle {
   o Person owner
}
```

<img width="1180" alt="image" src="https://github.com/user-attachments/assets/f651709f-1423-4342-83bc-5ec1e0da5f89">

## Context

Today you can run Concerto in two modes:
- Default: namespaces and imports are unversioned
- Strict: namespaces and imports are fully versioned

Strict mode is very useful in that it makes the dependency graph between concepts completely deterministic, given a single CTO file. I.e. you can take a single CTO file and follow all its versioned imports and build a deterministic graph of every element the model contains. The downside is that changes to namespaces that are "deep" in the dependency hierarchy cause a ripple of changes through out the entire graph. As the graph gets large this is untenable.

## Detailed Description

By supporting semver range imports these ripple updates of import versions are minimised, imports only need to be updated when the semver range constraint no longer matches. The downside is that the dependency graph from a CTO file is no longer purely defined by the CTO file itself, it depends on what other CTO files are present, and their versions. The so-called "package-lock.json" problem - there may need to be another mechanism to ensure deterministic versions of imported packages are used, to ensure fully reproducible builds.

### Ensuring Reproducible Builds

Below I illustrate an approach of writing back the resolved namespace version into the AST for the model, allowing semver imports to be "pinned" while maintaining them in the CTO or AST.

With semver import, with ability to specify a "resolved version" for an import:

```
namespace vehicle@1.0.0

@ResolvedVersion("1.0.1")
import person@1.x.{Person}

concept Vehicle {
   o Person owner
}
```

> Note: today we do not support decorators on imports, we should have to make changes to the meta model and the runtime to support this syntax.

1. Create CTO files Parent@1.0.0 and Child@1.0.1
2. Create a semver import of Child@1.x into Parent@1.0.0
3. Create a ModelManager with options `strict:true` and `semverImports:true` set (do we want a flag for this? Perhaps it should just be supported by default?)
4. Add Parent and Child to the ModelManager
5. Parent resolves imports from Child@1.0.1 and models validate
6. `ModelManager.resolveMetamodel` is used to create an AST that has the `ResolvedVersion` decorator added to all semver imports, capturing the version of the namespace that was used
7. AST can be stored and converted back to CTO for debugging or audit

When a reproducible ModelManager is required:

1. Create a ModelManager with options `strict:true` and `useResolvedImportVersions:true` set
2.  Add the ModelFiles for Parent and Child
3. The import of Child@1.x into Parent is ignored (because it has the `ResolvedVersion` decorator) and an import to version 1.0.1 is used. An exception is thrown if this exact version of the model file is not in the model manager.

When the ModelManager should pick up new namespace versions:

1. Create a ModelManager with options `strict:true` set and `semverImports:true` 
2.  Add the updated ModelFiles to the ModelManager, for example Child@1.1.0
3. Parent resolves imports from Child@1.1.0 and models validate
4. Call `ModelManager.resolveMetamodel` to store this configuration, if necessary

## Code Generation

When we generate code we will need to use the resolved imports, rather than imports than contain semver ranges.

### Tasks

- [x] Decide on semantics of semver imports (.x, ranges etc)
- [ ] Update the meta model to support semver imports
- [ ] Update the parser to support semver imports for CTO
- [ ] Convert AST back to CTO
- [ ] Update ModelFile to resolve imports with semver 
- [ ] Update VSCode extension
- [ ] Update the meta model to support decorators on imports
- [ ] Update the runtime to support decorators on imports

**Comment by mttrbrts** [comment]
Is there consensus on format of ranges we should support? Here are some alternatives
- `1.x` X-ranges
- `^1.0.0` Caret ranges
- `>=1.1.0 <1.2.0-0` desugared comparators
- `1` Partial ranges

Further, would we only support major version ranges (as above), or would we support more complex expressions, e.g.
- `1.2.x`
- `>=1 <=3.2`

As for the package-lock.json problem ...

We'll need to fully resolve versions to do validation and introspection inside the modelManager. It seems reasonable that we could dump the static versions for auditing purposes quite easily. However, the reproducibility problem seems harder, especially that we don't have a mechanism to pull model versions from a repository (we don't even have a standard repository protocol / index!). We could conclude that reproducibility is a client-concern for now! 😨

**Comment by dselman** [comment]
Semver imports also complicates caching / immutability of models. I.e. if I request namespace `vehicle@1.0.0` (along with its dependencies) the response payload cannot be cached using `vehicle@1.0.0` as the cache key.

**Comment by dselman** [comment]
Another consideration is that today the ModelFile has a map (importShortNames) from local short name to FQN that is populated from the AST. This approach would not work, because the FQN to use could change whenever a new model file is added to the ModelManager. We'd have to use logic similar to how strict:false wildcard imports are used, which are resolved on-demand.

**Comment by mttrbrts** [comment]
> I'm leaning towards just supporting x-ranges. E.g. 1.x or 1.2.x. I think that gives us what we know we need and should not complicate the parser too much. x-ranges are also simple to explain and to understand.

👍🏻 

> Do you think we should give people "the rope" and support x-ranges like x which allow for breaking changes?

Yes, I can imagine scenarios where version upgrades are forced despite the dependency not changing.

Here's the spec for x-ranges from npmjs semver package, https://www.npmjs.com/package/semver.

> Any of X, x, or * may be used to "stand in" for one of the numeric values in the [major, minor, patch] tuple.
> 
> * := >=0.0.0 (Any non-prerelease version satisfies, unless includePrerelease is specified, in which case any version at all satisfies)
> 1.x := >=1.0.0 <2.0.0-0 (Matching major version)
> 1.2.x := >=1.2.0 <1.3.0-0 (Matching major and minor versions)
> A partial version range is treated as an X-Range, so the special character is in fact optional.
> 
> "" (empty string) := * := >=0.0.0
> 1 := 1.x.x := >=1.0.0 <2.0.0-0
> 1.2 := 1.2.x := >=1.2.0 <1.3.0-0

**Comment by dselman** [comment]
Name collisions are possible - that could be breaking changes for specialised types. E.g. when I add a new property to a super type that conflicts with an existing property in a specialised type.

**Comment by mttrbrts** [comment]
Let's release this behind a feature flag.

**Comment by Anshukumar123975** [comment]
Hey @dselman , @mttrbrts , @DianaLease ,
I noticed this feature request but the last discussion was a few months ago. Is there still interest in adding semver support?
I'd like to contribute if this is something that's needed.

**Comment by mttrbrts** [comment]
> Hey @dselman , @mttrbrts , @DianaLease ,
> I noticed this feature request but the last discussion was a few months ago. Is there still interest in adding semver support?
> I'd like to contribute if this is something that's needed.


Yes, this is still in plan, and I'd welcome contributions! Please break down the work using the tasks list above. This is an expensive piece of work! 😀

We should also gate the change behind a feature flag, similar to what we did for ENABLE_MAP_TYPE

**Comment by Anshukumar123975** [comment]
Hey @mttrbrts ,
Thanks for confirming! I'm really excited about this feature and would love to contribute. This seems like a great learning opportunity, and I’m eager to work on it.
I’ve gone through the task list outlined in the issue, and I’m starting with the first task—defining the semantics of semver imports (.x, ranges, etc.)—and will aim to complete it as soon as possible.
Looking forward to collaborating and learning from the process!

**Comment by Anshukumar123975** [comment]
Hey @mttrbrts , @dselman , @DianaLease ,

After analyzing the **First task** and the discussions, here's a proposed approach to define the semantics of semver imports. The goal is to introduce a clear, predictable, and efficient way to resolve model dependencies while keeping complexity minimal.

### **Supported Semver Formats:-**

**X-Ranges :**   
a. 1.x -> Matches >=1.0.0 <2.0.0-0 (any minor/patch update within major version 1).
b. 1.2.x -> Matches >=1.2.0 <1.3.0-0 (any patch update within minor version 1.2).

**Partial Versions (Treated as X-Ranges) :** 

a. 1.2 -> Treated as 1.2.x,  matching >=1.2.0 <1.3.0-0.
b. 1 -> Treated as 1.x.x,  matching >=1.0.0 <2.0.0-0.

**Excluded for Now (Too Complex, Low Priority) :**

a. Complex ranges like >=1 <=3.2 will not be supported initially.
b. Pre-release versions (-alpha, -beta) are out of scope for now but can be revisited later.

### **Considerations:**

1. **Caching & Immutability:**

- Since semver imports introduce variability, caching logic must be adjusted. A model imported as vehicle@1. x. cannot be cached simply as vehicle@1.0.0.
- Potential solution: Store resolved versions explicitly in metadata.

2. **ModelFile & Import Resolution:**

- The importShortNames map (which resolves short names to Fully Qualified Names) needs to handle dynamic version resolution.
- Instead of static mappings, we might need on-demand resolution (similar to strict: false wildcard imports).

3. **Feature Flag for Controlled Rollout:**

- To manage risks, introducing a feature flag (ENABLE_SEMVER_IMPORTS) similar to ENABLE_MAP_TYPE.
- This ensures backward compatibility while allowing gradual adoption and testing.

**Next Steps:**

If this proposal aligns with expectations, I’ll move forward with Task-2:
Updating the meta model to support semver imports.

**Comment by Anshukumar123975** [comment]
Hey @mttrbrts , @dselman , 
Should I proceed with the next task - Updating the meta model to support semver imports?

**Comment by mttrbrts** [comment]
> Should I proceed with the next task 

@Anshukumar123975 Yes, please! It looks like you're on the right track.

**Comment by Anshukumar123975** [comment]
@mttrbrts Ok, I will be starting with the second task as soon as possible.
Thanks!

**Comment by Anshukumar123975** [comment]
Hi @mttrbrts @dselman ,
Due to my semester exams, I will be able to complete the second task a bit late. I will ensure it is completed promptly once my exams are over. 
Thank you for your patience and understanding.

**Comment by jamieshorten** [comment]
Reopening this because I'll have some resources to devote to it over the next few months.

**Comment by jamieshorten** [comment]
Assigning to @muhabdulkadir
